"""add column

Revision ID: 653c918be546
Revises: cf9cdcf64a83
Create Date: 2023-01-19 22:42:33.340762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "653c918be546"
down_revision = "cf9cdcf64a83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("about_author", sa.Text(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("profile_pic", sa.String(length=1000), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_pic")
        batch_op.drop_column("about_author")

    # ### end Alembic commands ###
