"""Add Posts Model

Revision ID: f51bb85fdd3d
Revises: ea1aec1573b8
Create Date: 2023-01-11 12:07:23.758308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f51bb85fdd3d"
down_revision = "ea1aec1573b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("date_posted", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("slug", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_column("slug")
        batch_op.drop_column("date_posted")
        batch_op.drop_column("author")

    # ### end Alembic commands ###
